/* ==================== DATA ==================== */
const REASONS=[{id:'growth',name:'Growth',hint:'Revenue'},{id:'profit',name:'Profitability',hint:'Margin'},
{id:'balance',name:'Balance sheet',hint:'Leverage'},{id:'value',name:'Valuation',hint:'Multiple'}];

const S=[
{sector:'Semiconductors',a:{t:'NORTHGATE MICRO',d:'Leading-edge logic foundry',g:34,m:28,l:.4,p:22,f:71},b:{t:'CALDWELL SEMI',d:'Legacy analog, mature markets',g:6,m:31,l:.9,p:11,f:88},better:'a',driver:'growth',market:'a',street:'Consensus underweight Northgate on cycle timing. Positioning is light.',why:'The cycle inflected and Northgate\u2019s order book compounded for eight quarters. Caldwell\u2019s better margin and conversion were mature-business artifacts with no volume growth to lever them. 22\u00d7 for 34% growth beat 11\u00d7 for 6%.'},
{sector:'Regional banking',a:{t:'MERIDIAN TRUST',d:'Deposit-funded commercial lender',g:9,m:34,l:1.2,p:8,f:79},b:{t:'PARKVIEW FINANCIAL',d:'Wholesale-funded, fast growth',g:4,m:30,l:3.8,p:6,f:44},better:'a',driver:'balance',market:'a',street:'Street rates both buy. Nobody is modelling a funding shock.',why:'Parkview looked cheaper on every headline measure. But funding structure is the entire business model in banking, and 3.8\u00d7 against wholesale deposits is a run risk, not a discount.'},
{sector:'Apparel retail',a:{t:'VELLA BRANDS',d:'Fast fashion, aggressive expansion',g:28,m:9,l:3.4,p:26,f:22},b:{t:'HARROW & CO',d:'Mid-market, disciplined footprint',g:11,m:14,l:1.1,p:15,f:81},better:'b',driver:'balance',market:'a',street:'Vella is a crowded long. Momentum funds own 14% of float.',why:'Vella\u2019s growth was funded by inventory and leases, not cash \u2014 22% conversion on a 9% margin at 3.4\u00d7 leaves no room for one bad season.',twist:'The market did not care for four more quarters. Vella rerated to 34\u00d7 before the model broke. Being early is the most expensive way to be right.'},
{sector:'Oil & gas',a:{t:'BASIN RIDGE',d:'Shale, acreage-led growth',g:45,m:22,l:4.6,p:9,f:31},b:{t:'CORVID ENERGY',d:'Diversified, hedged output',g:12,m:18,l:1.3,p:14,f:76},better:'b',driver:'balance',market:'b',street:'Price decks assume the strip holds. Few stress-test covenants.',why:'A 4.6\u00d7 levered producer converting 31% to cash is a call option on the commodity, not a business. When the strip fell 30%, covenants bound before the wells depleted.'},
{sector:'Pharmaceuticals',a:{t:'ALDEN THERAPEUTICS',d:'Two drugs, near patent expiry',g:3,m:32,l:1.9,p:9,f:91},b:{t:'KESTREL PHARMA',d:'Broad mid-stage pipeline',g:14,m:26,l:2.2,p:19,f:64},better:'b',driver:'growth',market:'b',street:'Alden screens as deep value on every quant model.',why:'Alden\u2019s 9\u00d7 was the market pricing a cliff it could see. High margin and 91% conversion on revenue that vanishes in 2027 is a liquidation, not quality. The 3% growth line was the tell.'},
{sector:'Airlines',a:{t:'ALTUS AIR',d:'Low-cost, rapid fleet growth',g:22,m:8,l:5.2,p:12,f:38},b:{t:'CORDEL AIRWAYS',d:'Network carrier, owned fleet',g:19,m:11,l:2.4,p:15,f:69},better:'b',driver:'balance',market:'b',street:'Consensus prefers Altus on unit cost. Leverage treated as a footnote.',why:'Airlines are a leverage business wearing an operations costume. Faster growth on a worse margin with double the debt survives only in good weather. Cordel\u2019s owned fleet was collateral when credit closed.'},
{sector:'Luxury goods',a:{t:'MAISON REVEL',d:'Heritage brand, controlled retail',g:16,m:27,l:.6,p:31,f:86},b:{t:'ATELIER NORD',d:'Accessible luxury, wholesale',g:18,m:12,l:2.1,p:17,f:58},better:'a',driver:'profit',market:'b',street:'Unusual options activity in Atelier. Someone is positioned for an event.',why:'27% versus 12% in the same category is not operational skill \u2014 it is pricing power, the only durable moat in luxury.',twist:'Atelier won the year on a takeover at a 40% premium. M&A is the largest single source of good-process-bad-outcome in research.'},
{sector:'Media',a:{t:'LUMEN STREAM',d:'Subscriber growth, heavy content spend',g:25,m:4,l:4.1,p:90,f:12},b:{t:'GRAYSON MEDIA',d:'Cable networks, cash-rich decline',g:8,m:21,l:1.6,p:13,f:94},better:'b',driver:'value',market:'b',street:'Lumen is the most-owned growth name. Grayson is universally hated.',why:'At 90\u00d7 and 12% conversion, Lumen needed a decade of flawless execution to justify entry. Grayson at 13\u00d7 converting 94% was priced for decline and declined less than feared.'},
{sector:'Homebuilding',a:{t:'STONEFIELD HOMES',d:'Land-light, option contracts',g:19,m:17,l:.3,p:7,f:74},b:{t:'ARBOR RESIDENTIAL',d:'Owned land bank',g:24,m:15,l:2.9,p:9,f:41},better:'a',driver:'balance',market:'a',street:'Both near book. Street sees them as interchangeable rate plays.',why:'Homebuilders die of land, not demand. Stonefield optioned lots instead of owning them, so when starts fell it walked from deposits rather than carrying inventory.'},
{sector:'Distribution',a:{t:'HALVERSON SUPPLY',d:'Regional MRO distributor',g:7,m:13,l:1.8,p:18,f:72},b:{t:'DEEPWELL INDUSTRIAL',d:'National, private-label mix',g:7,m:19,l:1.7,p:17,f:78},better:'b',driver:'profit',market:'b',street:'No differentiated view. Both rated hold.',why:'Identical growth, leverage and multiple \u2014 the only difference was six points of margin from private label and purchasing scale. When everything else is matched, the margin gap is the quality gap.'},
{sector:'E-commerce',a:{t:'TANDEM COMMERCE',d:'Marketplace, dominant share',g:30,m:15,l:.2,p:12,f:83},b:{t:'ORRIN GROUP',d:'Owned inventory, thinner scale',g:11,m:9,l:1.4,p:20,f:49},better:'a',driver:'value',market:'b',street:'Foreign investors exiting the jurisdiction wholesale. Flows one-directional.',why:'Three times the growth at a better margin, 83% conversion, almost no debt \u2014 at a 40% discount to the weaker operator. That is a dislocation, not a growth call.',twist:'A regulatory review froze the multiple for six quarters. Right on every metric; the discount widened before it closed.'},
{sector:'Telecom',a:{t:'BRIDGEPORT TEL',d:'Copper incumbent, high payout',g:2,m:24,l:3.1,p:8,f:52},b:{t:'NORWICH COMMS',d:'Fiber build, reinvesting',g:5,m:20,l:2.0,p:12,f:33},better:'b',driver:'value',market:'b',street:'Income funds hold Bridgeport for yield. Coverage thin either way.',why:'8\u00d7 looked like value, but those earnings funded a dividend from a shrinking copper base at 3.1\u00d7. Norwich\u2019s weak conversion was capex building an asset; Bridgeport\u2019s was maintenance on a melting one.'},
{sector:'Restaurants',a:{t:'CINDER & OAK',d:'Fast-casual, 6% of footprint built',g:21,m:11,l:2.6,p:28,f:67},b:{t:'MARLOWE DINING',d:'Casual dining, mature base',g:9,m:18,l:1.0,p:19,f:85},better:'a',driver:'growth',market:'a',street:'Street models 400 units. Management guides to 1,100.',why:'Marlowe had the better margin and cleaner balance sheet, and neither mattered. Cinder & Oak had 94% of its unit runway left, and unit count compounds while margin does not.'},
{sector:'Utilities',a:{t:'CASCADE POWER',d:'Regulated, large capex program',g:4,m:22,l:5.8,p:17,f:29},b:{t:'FAIRMONT ENERGY',d:'Regulated, build cycle complete',g:3,m:20,l:3.9,p:16,f:73},better:'b',driver:'balance',market:'a',street:'A rate case lands this quarter. Nobody has handicapped it publicly.',why:'Utilities are bond proxies financed with actual bonds. At 5.8\u00d7 into a rising-rate cycle, Cascade refinanced at prices that destroyed the returns the capex was built to earn.',twist:'Cascade won the period on a constructive rate case passing financing costs to ratepayers. Regulated outcomes are decided by commissions, not spreadsheets.'},
{sector:'Payments',a:{t:'PILOT PAY',d:'Merchant acquiring, land-grab pricing',g:38,m:6,l:.1,p:65,f:18},b:{t:'STRATTON NETWORKS',d:'Payment rails, entrenched',g:15,m:33,l:1.2,p:24,f:89},better:'b',driver:'profit',market:'b',street:'Pilot is the consensus disruptor long. Stratton called a melting ice cube.',why:'Pilot bought growth by underpricing \u2014 38% top line converting to a 6% margin and 18% cash. Stratton earned 33% on rails nobody could replicate. Margin tells you whether you own the network or rent it.'},
{sector:'Mining',a:{t:'REDSTONE MINERALS',d:'Copper, peak-price realizations',g:41,m:29,l:1.1,p:6,f:87},b:{t:'GALEN RESOURCES',d:'Diversified, mid-cycle assets',g:12,m:16,l:2.7,p:10,f:61},better:'b',driver:'value',market:'b',street:'Redstone screens as the cheapest large-cap miner in two decades.',why:'6\u00d7 on peak-cycle earnings \u2014 the cheapest-looking multiple in a commodity appears exactly at the top, and strong conversion at the peak confirms it rather than refuting it. Normalize the deck and 6\u00d7 becomes 19\u00d7.'},
{sector:'Automotive',a:{t:'HOLLAND MOTOR',d:'Legacy OEM, combustion mix',g:9,m:7,l:1.4,p:6,f:47},b:{t:'AXIOM VEHICLES',d:'Electric platform, ramping',g:33,m:14,l:.5,p:44,f:55},better:'b',driver:'growth',market:'b',street:'Holland is the value crowd\u2019s largest position. Axiom heavily shorted.',why:'The uncomfortable one: Axiom was better on growth, margin, leverage and conversion, and lost only on the multiple. Holland was cheap because its mix was structurally shrinking. Four of five metrics agreed \u2014 the fifth was what everyone anchored on.'},
{sector:'Healthcare',a:{t:'WESTMARK HEALTH',d:'Acute hospitals, strong payer mix',g:8,m:15,l:4.4,p:11,f:77},b:{t:'LINDEN CARE',d:'Rural, thin reimbursement',g:6,m:12,l:2.1,p:14,f:59},better:'a',driver:'profit',market:'b',street:'A reimbursement rule is out for comment. Most models assume no change.',why:'The reflex is to fear 4.4\u00d7, but hospital leverage is serviced by predictable cash \u2014 77% conversion says the cash is real. The payer mix behind the margin was the asset.',twist:'A rule change compressed the best-paying service line mid-year. Correct read of the business, adverse read of the regulator.'},
{sector:'Consumer staples',a:{t:'ORCHARD MILLS',d:'Branded food, premium shelf',g:12,m:16,l:2.8,p:21,f:80},b:{t:'BAYSIDE FOODS',d:'Private-label manufacturer',g:6,m:23,l:1.5,p:19,f:66},better:'a',driver:'growth',market:'a',street:'Street sees Bayside as the margin winner. Volume mix under-analysed.',why:'In inflation the question is who raises price without losing volume. Orchard\u2019s 12% was almost all price and mix passing through \u2014 proof of brand. Bayside\u2019s fatter margin came from contracts that reset against it.'},
{sector:'Data centers',a:{t:'KEYSTONE DIGITAL',d:'Hyperscale, pre-leased pipeline',g:17,m:30,l:6.2,p:38,f:68},b:{t:'ARDEN INFRASTRUCTURE',d:'Colocation, enterprise tenants',g:10,m:34,l:4.1,p:26,f:75},better:'a',driver:'growth',market:'a',street:'Leverage screens flag Keystone. Lease backlog is not in the screens.',why:'Both carry the leverage this asset class always carries \u2014 the difference is what the debt buys. Keystone pre-leased to investment-grade tenants before breaking ground, converting leverage into contracted revenue.'}];

const ITEMS={
 acct:{n:'Accounting course',cost:1500,ef:'Adds cash conversion to every company card. Several names are unreadable without it.'},
 term:{n:'Market terminal',cost:6000,ef:'Shows how the street is positioned before you commit. Crowding is where the surprises come from.'},
 app:{n:'Fund a side app',cost:7500,ef:'Three months to build, then $700/mo. Income that does not depend on your calls.'}
};
